export const GET_THREEDAY_FORCAST_FAILED = "GET_THREEDAY_FORCAST_FAILED";
export const GET_THREEDAY_FORCAST_SUCCESS = "GET_THREEDAY_FORCAST_SUCCESS";
export const GET_WEEKLY_SUMMARY_SUCCESS = "GET_WEEKLY_SUMMARY_SUCCESS";
export const GET_ALERTS_SUCCESS = "GET_ALERTS_SUCCESS";
export const GET_THREEHOUR_FORCAST = "GET_THREEHOUR_FORCAST";